#SPDX-License-Identifier: MIT-0
---
- name: Create docker-compose.yml from template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_dir }}/docker-compose.yml"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0600"
    backup: true

- name: Check for existing Docker Compose .env file
  ansible.builtin.stat:
    path: "{{ docker_dir }}/.env"
  register: env_file_stat

- name: Create Docker Compose .env file from template if missing
  ansible.builtin.template:
    src: .env.j2
    dest: "{{ docker_dir }}/.env"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0600"
    backup: true
  when: not env_file_stat.stat.exists

- name: Ensure auto-go-app env directory structure
  ansible.builtin.file:
    path: "{{ docker_dir }}/envs/auto-go-app"
    state: directory
    mode: "0750"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Create auto-go-app .env file from template
  ansible.builtin.template:
    src: applications/auto-go-app/.env.j2
    dest: "{{ docker_dir }}/envs/auto-go-app/.env"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0640"
    backup: true

- name: Ensure hello-world env directory structure
  ansible.builtin.file:
    path: "{{ docker_dir }}/envs/hello-world"
    state: directory
    mode: "0750"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Create hello-world .env file from template
  ansible.builtin.template:
    src: applications/hello-world/.env.j2
    dest: "{{ docker_dir }}/envs/hello-world/.env"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: "0640"
    backup: true
